### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by aditi48n** [UBC-MDS/dropout-predictions#8]
Congratulations on finishing milestone 1! We can see you put a lot of work into this project, nice work! Below we list some specific feedback you can use to improve your project. We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project. If anything is unclear, please feel free to ask questions in this issue thread.

Code of Conduct.md
- [x] #24
**Comment:** Not mentioned within the document. 

CONTRIBUTING.md
- [x] #23
**Comment:** Core teams contribution workflow is not mentioned and text is linked but does not lead anywhere. Fix that. 

License 
- [x] #22
**Comment:** Missing license

Project proposal
- [x] #25
**Comment:** Document has grammatical errors. Proofread going forward. 
**General Comment:** The question you want to answer through your analysis is written out as a statement. Going forward, write it as a question in a separate line so it is clear to someone reading your proposal what you want to answer. 

A script that downloads and saves the data
- [x] #12
**Comment:** The readme file should contain instructions on how to run the script. None have been provided. 

Exploratory data analysis in a literate code document
- [x] #11
**Comment:** Captions are below the table.
- [x] #27
**Comment:** Usage instructions not specified

Expectations
- [x] #10
**Comment:** Other commits on main branch other than the ones created for merge.

**Comment by caesarw0** [comment]
closing this issue (milestone 4 completed)
